### ISSUE TITLE
Preferences button is misaligned on Windows

### ISSUE THREAD

**Issue by GeorgeHahn** [Frique/N1-Berend#1]
This is especially noticeable when using the two panel view:

![2016_01_24_15_12_42_settings](https://cloud.githubusercontent.com/assets/502747/12538673/66ce67f2-c2ad-11e5-9857-8962156ac428.png)

**Comment by berend-de-jong** [comment]
From the screenshot I see there are some more alignment issues on Windows. Hope to fix them sometime soon. Thanks for the feedback!

**Comment by gwigz** [comment]
Preferences button seems to be fine now, not sure if anything was changed recently. Aside from that, Windows is also experiencing #5.

Theme looks really pretty though, good stuff @Frique!

**Comment by berend-de-jong** [comment]
This should be better in v1.3.1.
