### ISSUE TITLE
UI Bug Win 7 Activity Icon

### ISSUE THREAD

**Issue by grand-lotus-iroh** [Frique/N1-Berend#10]
Activity icon gets overlapped by search input. 
Once you click icon (or try to) it disappears until restart.

Perhaps move search box 20 pixels to the right?

Before click
![nylas_2016-05-21_03-24-47](https://cloud.githubusercontent.com/assets/1291364/15447116/ab9d2b40-1f03-11e6-98f8-bdc781566396.png)

After click
![nylas_2016-05-21_03-26-31](https://cloud.githubusercontent.com/assets/1291364/15447121/ded2c772-1f03-11e6-9738-21f02fa0ee43.png)

**Comment by berend-de-jong** [comment]
Fixed in 1.3.8: https://github.com/Frique/N1-Berend/releases
