### ISSUE TITLE
UI Bug Win 7 Modal Compose (missing bg overlay)

### ISSUE THREAD

**Issue by grand-lotus-iroh** [Frique/N1-Berend#11]
When I compose new message, the background doesn't have dark bg opacity.

**Comment by berend-de-jong** [comment]
Could you provide a screenshot of this?

**Comment by grand-lotus-iroh** [comment]
On the front page, https://github.com/Frique/N1-Berend, you'll see the screenshot with Compose Window. Notice how you have a dimmed BG overlay? That is missing from both Windows and Ubuntu 16. When I press "compose" button in upper left corner, the rgba (0,0,0,0.15) is missing.

Also, if I may, what OS are you using?

**Comment by berend-de-jong** [comment]
Oh I see. I'm using OSX and the overlay in the screenshot is actually caused by the app HazeOver. So it's not part of the theme, sorry.
