### ISSUE TITLE
Unable to adjust width of primary (L) sidebar

### ISSUE THREAD

**Issue by grand-lotus-iroh** [Frique/N1-Berend#12]
If I change your theme, to a stock one, my mouse changes cursor and allows me to gain precious real-estate. Sadly, once Berend is activated, that ability is removed and I lose about 1 inch on my monitor to wasted white space.
- Using Ubuntu 16
- Two Panel layout
- Shift + ? > Appearance > Change Theme > Pick Light > Press X and navigate mouse to sidebar

**Comment by berend-de-jong** [comment]
Right. This is currently a design decision, so i'll close the issue for now and consider changing it in the future.
