### ISSUE TITLE
Overlay

### ISSUE THREAD

**Issue by rawnly** [Frique/N1-Berend#15]
![schermata 2016-12-28 alle 14 24 39](https://cloud.githubusercontent.com/assets/16429579/21522860/809be274-cd09-11e6-8909-2e1203100f34.png)

N1 Version:  **0.4.402 (0.4.402)**
macOS: **10.12.2**

Please fix it! 

Latest berend & Latest N1

**Comment by neo21670** [comment]
I'd like to confirm this bug under N1 v0.4.402 and mac OS 10.12.2 with all the updates installed.

**Comment by berend-de-jong** [comment]
Yeah sorry, haven't had time to keep the theme updated. Unfortunately it requires a lot of maintenance because almost each N1 update breaks the theme in some way.

Pull requests are welcome!
