### ISSUE TITLE
Letter "g" round bottom cut off in message list

### ISSUE THREAD

**Issue by mbilker** [Frique/N1-Berend#2]
**N1 Version:** 0.3.46-master
**Berend Version:** master
**OS:** Arch Linux 2016.01.24

_Description:_
The letter "g" is cut off in the message list and is particularly annoying. Your screenshot does not display this, so I think it is a Linux issue. Maybe the cell height can be increased a slight amount.

_Expected_Result:_
The letter "g" is not cut off in the message list.

Screenshots:
![2016-01-24-23-39-45_219x152](https://cloud.githubusercontent.com/assets/1266541/12542692/6a34031a-c2f4-11e5-82b5-4cb7626528ee.png)
![2016-01-24-23-41-08_215x152](https://cloud.githubusercontent.com/assets/1266541/12542693/6a3590b8-c2f4-11e5-8e9e-136eb55493b0.png)

**Comment by mbilker** [comment]
I updated my comment to display the Berend version I am using, which is the `master` git branch.

**Comment by berend-de-jong** [comment]
It's probably because the line-height is set to 1. Thanks for the details! I'll try to update this.
