### ISSUE TITLE
No highlight or cursor on the current selection

### ISSUE THREAD

**Issue by tito** [Frique/N1-Berend#3]
Nylas have a "blue" cursor that indicate the current mail selected in the list/inbox view. The arrow cursor allow to move up/down the list, x to select. Everything works, but the theme doesn't show where the cursor is :)

Using Elementary OS/Linux, Nylas 0.3.45, N1-Berend 1.0.1

**Comment by berend-de-jong** [comment]
Interesting. I removed the blue line because it doesn't fit the theme (in favor of other "active" states) however they don't seem to apply during keyboard navigation. Thanks for reporting. Will check it out.

**Comment by zlatkobijelic** [comment]
Also I noticed that the currently selected email also has the same styles as **Unread** emails any way to differentiate those?

**Comment by berend-de-jong** [comment]
Did some changes in this matter and released v1.1.0.

**Comment by tito** [comment]
Works great, thanks you :)
