### ISSUE TITLE
selected items invisible

### ISSUE THREAD

**Issue by IzsakiRobi** [Frique/N1-Berend#4]
Hi!

First Thank you for goooood theme! 😊
Bug: if select some mail items, control+click or shift+click, not seen any visible changes...

Use in Ubuntu Gnome

rob

**Comment by berend-de-jong** [comment]
Glad you like it!
Will check this issue out. I personally prefer the single-pane view so I never noticed :)

**Comment by IzsakiRobi** [comment]
Thanx 😉

**Comment by IzsakiRobi** [comment]
Hi!

any change?

**Comment by berend-de-jong** [comment]
Not yet. Will push an update soon to also address the newest N1 features.

**Comment by IzsakiRobi** [comment]
Thanx! Waiting 😊

**Comment by berend-de-jong** [comment]
This is addressed in 1.3.0: https://github.com/Frique/N1-Berend/releases

**Comment by IzsakiRobi** [comment]
Thanks! 
beautiful! But one bug again :)
Compose Button missaligned.... I open new ticket.
