### ISSUE TITLE
Compose Button missalign in N1 0.4.10 Berend 1.3.0

### ISSUE THREAD

**Issue by IzsakiRobi** [Frique/N1-Berend#5]
In Linux, Ubuntu Gnome 16.04:

![compose](https://cloud.githubusercontent.com/assets/15942662/13372796/f2eca378-dd53-11e5-9390-8d97dccc8557.png)

**Comment by berend-de-jong** [comment]
Thanks. Haven't tested in Ubuntu yet.

**Comment by berend-de-jong** [comment]
Should be fixed in 1.3.1

**Comment by gwigz** [comment]
It's fixed on Windows, cheers! :+1:
