### ISSUE TITLE
Preview for visual theme picker

### ISSUE THREAD

**Issue by jackiehluo** [Frique/N1-Berend#6]
Hey, @Frique! I'm part of the Nylas team, and we're about to land a new visual theme picker that'll allow people to preview and view color palettes for themes. We pull a few major colors from the theme's UI variables to create the palette, but we've also added a way to override them manually with a `theme-colors.less` file for themes. Just wanted to let you know in advance in case you want to change anything! Here's how your theme looks, and you can find the details for how we assign the colors in Part 5 of [these instructions for creating themes](https://github.com/nylas/N1-theme-starter).

<img width="110" alt="screen shot 2016-03-04 at 4 35 48 pm" src="https://cloud.githubusercontent.com/assets/8452682/13544131/8fe0ce2a-e227-11e5-8388-fbf9c9e204c0.png">

**Comment by berend-de-jong** [comment]
Thanks. This is now applied.
