### ISSUE TITLE
UI Bug in Quick Reply

### ISSUE THREAD

**Issue by PatrickJGabriel** [Frique/N1-Berend#8]
I'm not sure if this is exclusively due to N1's built in Quick Reply or what, but it seems the last two menu items are always covered by the window as shown in the screenshot i've attached. 

![screenshot 2016-05-01 11 04 40](https://cloud.githubusercontent.com/assets/11248222/14942506/d11a4168-0f8c-11e6-9607-96630c8c81ba.png)

**Comment by leovarmak** [comment]
@Manevolence The issue has been fixed now. Please download the latest release.

**Comment by berend-de-jong** [comment]
Hi. I can't seem to reproduce this. In what situation does this occur exactly? And yes, updating to the latest version of the theme might help.
