### ISSUE TITLE
UI issues ever since we had a Update

### ISSUE THREAD

**Issue by leovarmak** [Frique/N1-Berend#9]
I facing a lot of UI issues. I think you need to tweak it once again because of this update.

**Comment by berend-de-jong** [comment]
Yeah every N1 update seems to break some of the theme. It's unavoidable. Haven't had time to update it yet so I'd advise to switch themes in the meantime.

**Comment by leovarmak** [comment]
In case you make some changes. how will you test them ? like you download them install... change and install... until its perfect ?

**Comment by berend-de-jong** [comment]
To develop the theme, you'd activate the theme from the folder with the git repository in it. Then simply edit the .less files and refresh N1 (opt-cmd-L on mac) to see the changes. When done, commit the changes.
Also use the dev-tools (opt-cmd-I) to browse the markup and test styles.

**Comment by leovarmak** [comment]
How can I delete the old theme which is installed on Mac ?

**Comment by leovarmak** [comment]
Well I tried to tweak but everything is greek and latin to me. So I guess I will wait till you correct it :)

**Comment by berend-de-jong** [comment]
Ok, thanks for the effort!

**Comment by berend-de-jong** [comment]
An update is now released dealing with some of the N1 version 0.4.33 issues. Let me know if there's anything left.

**Comment by leovarmak** [comment]
@Frique Thanks. I will let you know if anything is wrong :)
